import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useOfflineSync } from "@/hooks/use-offline-sync";
import { getCaseDetails, getCases, type CaseDetails, type CaseRow } from "@/lib/office-lists";
import { getCurrentMembership, type OfficeMembership } from "@/lib/office-data";
import { canViewCaseCount, canViewFinancials } from "@/lib/office-permissions";

export default function CasesScreen() {
  const colors = useColors();
  const [membership, setMembership] = useState<OfficeMembership | null>(null);
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [selected, setSelected] = useState<CaseDetails | null>(null);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const offline = useOfflineSync(membership?.office_id);
  const load = useCallback(async () => { if (!membership) return; setLoading(true); setError(""); try { setCases(await getCases(membership.office_id)); } catch (e) { setError(e instanceof Error ? e.message : "تعذر تحميل القضايا"); } finally { setLoading(false); } }, [membership]);
  useEffect(() => { getCurrentMembership().then(setMembership).catch((e) => setError(e instanceof Error ? e.message : "تعذر معرفة المكتب")); }, []);
  useEffect(() => { load(); }, [load]);
  const open = async (item: CaseRow) => { if (!membership) return; try { setError(""); setSelected(await getCaseDetails(membership.office_id, item.id, canViewFinancials(membership.role))); } catch (e) { setError(e instanceof Error ? e.message : "تعذر تحميل تفاصيل القضية"); } };
  const visibleCases = cases.filter((item) => { const value = `${item.case_code ?? ""} ${item.case_number ?? ""} ${item.client_name ?? ""} ${item.opponent_name ?? ""} ${item.client_phone ?? ""} ${item.case_subject ?? ""}`.toLowerCase(); return value.includes(query.trim().toLowerCase()); });
  if (loading && !cases.length) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={colors.primary} /><Text className="text-sm text-muted mt-3">جاري تحميل القضايا...</Text></ScreenContainer>;
  return <ScreenContainer className="px-5" safeAreaClassName="bg-background">
    <View className="mt-5 mb-4" style={{ direction: "rtl" }}><Text className="text-2xl font-bold text-foreground">القضايا</Text><Text className="text-sm text-muted mt-1">ابحث واعرض العميل والخصم والجلسات والحساب.</Text></View>
    <View className="rounded-2xl px-4 py-3 mb-4 flex-row items-center justify-between" style={{ backgroundColor: offline.isOnline ? `${colors.success}18` : `${colors.warning}22`, direction: "rtl" }}><Text className="text-xs font-bold" style={{ color: offline.isOnline ? colors.success : colors.warning }}>{offline.isOnline ? "متصل" : "غير متصل"}</Text>{canViewCaseCount(membership?.role) ? <Text className="text-xs text-muted">{cases.length} قضية</Text> : <Text className="text-xs text-muted">بحث ومتابعة العمل</Text>}</View>
    {error ? <Text className="text-xs mb-3" style={{ color: colors.error, textAlign: "right" }}>{error}</Text> : null}
    {selected ? <CaseDetailsCard details={selected} colors={colors} showFinance={canViewFinancials(membership?.role)} onClose={() => setSelected(null)} /> : <><TextInput value={query} onChangeText={setQuery} placeholder="اسم العميل أو الخصم أو كود القضية أو رقمها" placeholderTextColor={colors.muted} style={{ backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11, color: colors.foreground, textAlign: "right", marginBottom: 14 }} /><FlatList data={visibleCases} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingBottom: 30 }} renderItem={({ item }) => <Pressable onPress={() => open(item)} style={({ pressed }) => [{ backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 16, marginBottom: 12, opacity: pressed ? 0.7 : 1 }]}><Text className="text-base font-bold text-foreground" style={{ textAlign: "right" }}>{item.case_code || item.id}</Text><Text className="text-sm text-muted mt-2" style={{ textAlign: "right" }}>{item.client_name || "بدون اسم عميل"}</Text><Text className="text-xs text-muted mt-1" style={{ textAlign: "right" }}>{item.opponent_name ? `الخصم: ${item.opponent_name}` : item.case_subject || item.court_name || "بدون وصف"}</Text></Pressable>} ListEmptyComponent={<Text className="text-sm text-muted text-center py-8">لا توجد قضايا مطابقة.</Text>} /></>}
  </ScreenContainer>;
}
function CaseDetailsCard({ details, colors, showFinance, onClose }: { details: CaseDetails; colors: ReturnType<typeof useColors>; showFinance: boolean; onClose: () => void }) {
  const c = details.case;
  return <FlatList data={details.sessions} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListHeaderComponent={<View style={{ direction: "rtl" }}><Pressable onPress={onClose} style={{ alignSelf: "flex-start", paddingVertical: 8 }}><Text style={{ color: colors.primary, fontWeight: "700" }}>العودة للقضايا</Text></Pressable><Text className="text-xl font-bold text-foreground mt-2">{c.case_code || c.id}</Text><Text className="text-sm text-muted mt-2">{c.case_number ? `رقم القضية: ${c.case_number}/${c.case_year ?? ""}` : ""}</Text><Text className="text-base font-bold text-foreground mt-4">العميل</Text><Text className="text-sm text-muted mt-1">{c.client_name || "غير مسجل"} · {c.client_phone || "بدون هاتف"}</Text><Text className="text-sm text-muted mt-1">{c.client_address || "بدون عنوان"}</Text><Text className="text-base font-bold text-foreground mt-4">الخصم</Text><Text className="text-sm text-muted mt-1">{c.opponent_name || "غير مسجل"} · {c.opponent_phone || "بدون هاتف"}</Text><Text className="text-sm text-muted mt-1">{c.opponent_role || ""} {c.opponent_address || ""}</Text>{showFinance ? <><Text className="text-base font-bold text-foreground mt-4">الحساب</Text><Text className="text-sm text-muted mt-1">الأتعاب: {details.fees?.total ?? 0} · المدفوع: {details.totals.paid} · المتبقي: {details.totals.remaining}</Text><Text className="text-sm text-muted mt-1">المقبوضات: {details.totals.income} · المصروفات: {details.totals.expenses} · الصافي: {details.totals.net}</Text></> : null}<Text className="text-base font-bold text-foreground mt-4 mb-3">الجلسات ({details.sessions.length})</Text></View>} renderItem={({ item }) => <View style={{ backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 13, marginBottom: 9, direction: "rtl" }}><Text className="text-sm font-bold text-foreground">{item.session_date}</Text><Text className="text-xs text-muted mt-1">{item.case_status || "بدون حالة"} {item.decision ? `· ${item.decision}` : ""}</Text></View>} ListEmptyComponent={<Text className="text-sm text-muted text-center py-5">لا توجد جلسات مسجلة.</Text>} />;
}
