import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { getCurrentMembership, type OfficeMembership } from "@/lib/office-data";
import { supabase } from "@/lib/supabase";

type Notice = { id: string; title: string; action: string; entity_type: string; actor_role: string | null; details: { name?: string }; created_at: string; read_at: string | null };
export default function NotificationsScreen() { const colors=useColors(); const [membership,setMembership]=useState<OfficeMembership|null>(null); const [rows,setRows]=useState<Notice[]>([]); const [loading,setLoading]=useState(true); const load=useCallback(async()=>{const m=await getCurrentMembership(); if(!m||m.role!=="manager"){router.replace("/(tabs)");return;} setMembership(m); const {data,error}=await supabase.from("office_notifications").select("id,title,action,entity_type,actor_role,details,created_at,read_at").eq("office_id",m.office_id).order("created_at",{ascending:false}).limit(100); if(error)throw error; setRows((data||[]) as Notice[]); await supabase.from("office_notifications").update({read_at:new Date().toISOString()}).eq("office_id",m.office_id).is("read_at",null);},[]); useEffect(()=>{load().catch(()=>undefined).finally(()=>setLoading(false));},[load]); if(loading)return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={colors.primary}/></ScreenContainer>; if(!membership)return null; return <ScreenContainer className="px-5" safeAreaClassName="bg-background"><Text className="text-2xl font-bold text-foreground mt-5 mb-2" style={{textAlign:"right"}}>إشعارات المكتب</Text><Text className="text-sm text-muted mb-5" style={{textAlign:"right"}}>كل إضافة أو تعديل من فريق المكتب تظهر هنا.</Text><FlatList data={rows} keyExtractor={x=>x.id} renderItem={({item})=><View className="rounded-2xl p-4 mb-3" style={{backgroundColor:colors.surface,borderWidth:1,borderColor:item.read_at?colors.border:colors.primary,direction:"rtl"}}><Text className="text-sm font-bold text-foreground">{item.title}</Text><Text className="text-xs text-muted mt-2">الدور: {item.actor_role||"عضو"} · العملية: {item.action}</Text><Text className="text-xs text-muted mt-1">{item.details?.name||"بيان جديد"} · {new Date(item.created_at).toLocaleString("ar-EG")}</Text></View>} ListEmptyComponent={<Text className="text-sm text-muted text-center py-8">لا توجد إشعارات جديدة.</Text>} /></ScreenContainer>; }
